backend:
  name: git-gateway
  branch: main

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: "test"
    label: "Test"
    files:
      - label: "Hello world"
        name: "hello"
        file: "static/test.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
